### ISSUE TITLE
Better config page 

### ISSUE THREAD

**Issue by quafzi** [dime-timetracker/dime-frontend#4]
Config should be grouped, each group should have a title and may contain configuration items, that have a title, a description, an input type, a default value, a weight (for the items order) and may have a presave and a postsave function. 

Modules should be able to add config groups and/or config items easily.

**Comment by nogo** [comment]
I added a core/configuration.js to handle local configuration. We should you mediator pattern to link to settings.

**Comment by quafzi** [comment]
I just created a `configuration` branch to create an enriched, better usable configuration interface.

**Comment by quafzi** [comment]
Fixed in 6f2fa93 and 2013c58.
